### root access
GET http://localhost:8001


### create new user
POST http://localhost:8001/api/v1/create-account
Content-Type: application/json

{
    "email":"abc@gmail.com",
    "password":"123456",
    "fName":"amrit",
    "lName":"sapkota",
    "address":"3-5 Burlington Road Homebush"
   
}

### login api endpoint
POST http://localhost:8001/api/v1/login
Content-Type: application/json

{
    "email":"abc@gmail.com",
    "password":"123456"
}

##Category
### fetch category end point
GET http://localhost:8001/api/v1/category


###fetch products by using categoryID
GET http://localhost:8001/api/v1/category/609e75e9f1af6621b4f0f417


##product
###fetch all products
GET http://localhost:8001/api/v1/product


### fetchproducts by slug
GET http://localhost:8001/api/v1/product/Almond-Milk



###fetch the products to be in the cart
POST http://localhost:8001/api/v1/cart
Content-Type: application/json

{
"ids":["609e753ff1af6621b4f0f414","609e7572f1af6621b4f0f415"]
}


###insert product reviews
POST http://localhost:8001/api/v1/reviews
Content-Type: application/json

{
"reviewsObj":"good pGFGroduct"
}



###logout api
POST http://localhost:8001/api/v1/logout
Content-Type: application/json

{
"_id":"60a5ec7e4d84722910d67b82"
}


###GET ACCESS TOKEN API
GET http://localhost:8001/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BnbWFpbC5jb20iLCJpYXQiOjE2MjIwODg5MTMsImV4cCI6MTYyNDY4MDkxM30.K8pvlxRJCPVD7CmDFSNMV5ctcLEHYVPhSh6uCSGxgic



